[local]
localhost

[mongodb]
localhost     

[catalogue]
localhost

[redis]
redis-dev.daws-88s.online

[user]
user-dev.daws-88s.online

[cart]
cart-dev.daws-88s.online

[mysql]
mysql-dev.daws-88s.online

[shipping]
shipping-dev.daws-88s.online

[rabbitmq]
rabbitmq-dev.daws-88s.online

[payment]
payment-dev.daws-88s.online

[frontend]
frontend-dev.daws-88s.online
